spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/video?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接最大存活时间（必须小于 MySQL 的 wait_timeout）
      max-lifetime: 300000       # 300 秒（5 分钟）
      # 空闲连接超时时间
      idle-timeout: 60000        # 60 秒
      # 连接验证超时时间
      validation-timeout: 5000   # 5 秒
      # 连接池初始化后执行的测试查询
      connection-test-query: SELECT 1
      # 连接池最小空闲连接数
      minimum-idle: 2
      # 连接池最大连接数（根据业务调整）
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: sF3x7Q9zV2bY8pW6tR5uH0jK1lM4nO7iP8qA2dC4eG5vB6wX
  expiration: 86400000 # 24 小时

